### ISSUE TITLE
handling of "set run 1"

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#1]
Hi,

The command "set run 1" needs to be handled in a special manner. When this command is executed, communication to the controller should stay "open" indefinitely while the ventilation is running/executing. Currently, running "mvm-control set run 1" returns "Success", but the program exits and the ventilation does not run.

This is an issue whose solution will require some thought since useful data-taking requires executing "set run 1", while simultaneously logging the readout data. From the user point of view, this is an essential requirement. 

thanks,
Michael

**Comment by bryerton** [comment]
That's strange, why would it not stay on?

Have you tried using the new --use-log feature? I recommend modifying a
previously taken log to have run set to '1' in the JSON settings object,
then putting that log in as an option to --use-log

I'm free at this exact moment if you have a zoom

**Comment by leyton-cern** [comment]
I'm not sure, but I can hear a click from the valve regulation that tells me that I've somehow lost communication to the controller. 

The --use-log features does work, so thank you for that.

When trying to exit console_log with a keyboard interrupt, the program can sometimes get stuck inside the "while True" of the set_mvm_param method, in the event that the controller is returning something unexpected values. It has happened to me a few times and the only way out is to close the terminal window. Could you please add a timeout here?

**Comment by bryerton** [comment]
Will do,  do you think I should rename use-log to use-cfg, it seems
appropriate, as you can use a file devoid of log data, and might be clearer?

**Comment by leyton-cern** [comment]
Since we will want to move to storing and re-loading config files (perhaps with a .cfg extension?), I think it's a good idea to rename.

**Comment by bryerton** [comment]
This has been resolved as of version 1.2.2. The MVM was resetting on the opening of the serial port due to the DTR pin. The script now attempts to pick a setting that works for windows and linux, and is over-rideable with the '--force-dtr' option
