### ISSUE TITLE
\n after clog data

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#11]
Hi Bryerton,
Would you consider adding a '\n' after the clog string output in the .json file? It would improve readability and might make it easier to parse later. I don't know if it would screw up the current analysis code or .csv translator, but it did exist in an earlier version of mvm-control.
thanks,
Michael

**Comment by bryerton** [comment]
It disappeared? I'll look into it

**Comment by bryerton** [comment]
Fixed in version 1.4.3
