### ISSUE TITLE
str vs. bytes - additional decode()

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#2]
Hi,

Using Python 3.8.2, Windows 10 and Huzzah FSP32 firmware from 15 April, I had to add .decode() to the following string manipulations:

line 158: 
response = ser.read_until().strip().lower().decode()
line 319:
resp = ser.readline().strip().decode()

-Michael

**Comment by bryerton** [comment]
Hi Michael, thanks for the find, I'll add the fixes in.

I'm hoping to setup pytest and tox tonight or this weekend, and I'll make
sure to add py38 to the test environment.

**Comment by bryerton** [comment]
Fixed, and added some simple tests for py2.7,3.6, and 3.8
