### ISSUE TITLE
controller returns unexpected strings

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#3]
Often times, our controller in Napoli returns unexpected values from simple "get" commands. This is not the fault of mvm-control, but it would be smart to manage this. For example, here is output from consecutive "get all" commands, spaced 1-2 seconds apart:

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'OFFSET:            -0.29')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
-0.01,239.54,21.70,0.00,0.00,0.00,24.00,0,100.00,0.00,0.00,0.00,0.00

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
0.00,0.06,21.70,0.00,0.00,0.00,24.00,0,100.00,0.00,0.00,0.00,0.00

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'OFFSET:            4.15')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'SCAN I2C BUS: 0')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
Error parsing response! (b'SFM sensor probing failed')
None

C:\Users\DarkSideWS06\Documents\mvm>mvm-control -p COM3 get all
-0.02,0.00,21.70,0.00,0.00,0.00,24.00,0,100.00,0.00,0.00,0.00,0.00

**Comment by leyton-cern** [comment]
Sometimes there are address issues reported back:

C:\Users\DarkSideWS06\Documents\GitHub\mvm-control>python mvm_control.py -p COM3 get flow
b'I2C device found at address 0x70'
Error parsing response! (b'I2C device found at address 0x70')
None

C:\Users\DarkSideWS06\Documents\GitHub\mvm-control>python mvm_control.py -p COM3 get flow
b'OFFSET:            -0.53'
Error parsing response! (b'OFFSET:            -0.53')
None

C:\Users\DarkSideWS06\Documents\GitHub\mvm-control>python mvm_control.py -p COM3 get flow
b'SCAN I2C BUS: 0'
Error parsing response! (b'SCAN I2C BUS: 0')
None

**Comment by leyton-cern** [comment]
My suspicions is that the controller sometimes sends back data that was not specifically requested by the user. Here are some clues:

C:\Users\DarkSideWS06\Documents\mvm>python mvm_control.py -p COM3 console_log console_test.json
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')
Error parsing response! (b'SFM sensor probing failed')

C:\Users\DarkSideWS06\Documents\mvm>python mvm_control.py -p COM3 console_log console_test.json
Error parsing response! (b'OFFSET:            -1.07')
Error parsing response! (b'SENSOR:           2')
Error parsing response! (b'SENS_T1:          14662')
Error parsing response! (b'OFF_T1:           9565')
Error parsing response! (b'TCS:              3651')
Error parsing response! (b'TCO:              3367')
Error parsing response! (b'TREF:             44202')
Error parsing response! (b'TEMPSENS:         7880')
Error parsing response! (b'')
Error parsing response! (b'OFFSET:            4.16')
Error parsing response! (b'SENSOR:           3')
Error parsing response! (b'SENS_T1:          14613')
Error parsing response! (b'OFF_T1:           8622')
Error parsing response! (b'TCS:              3697')
Error parsing response! (b'TCO:              2519')
Error parsing response! (b'TREF:             44357')
Error parsing response! (b'TEMPSENS:         7838')

**Comment by bryerton** [comment]
Does this only happen when console log is on?

**Comment by leyton-cern** [comment]
It's an intermittent problem, which makes it somewhat difficult to debug, but it happens often enough that it is a real issue.

I don't think so because there are errors from simple "get" commands.

**Comment by bryerton** [comment]
I will look into it early this afternoon and get back to you as soon as
possible

**Comment by leyton-cern** [comment]
This is definitely something on the controller side, so I will also communicate this issue to Andrea and put you in cc.

**Comment by bryerton** [comment]
Once console is turned on, I believe it will spew extra messages beyond the
log data , it's really a mode for pure diagnostic use. If console is 0, and
these extra messages still occur then this is a bug.

**Comment by leyton-cern** [comment]
I just checked by explicitly setting "set console 0" and then only executing "get all" commands. I get many empty strings, but also strings containing "OFFSET:   4.18". So I believe it is not only due to console 1.

**Comment by leyton-cern** [comment]
As per an e-mail discussion with Andrea, this issue is likely due to the Adafruit controller resetting each time the serial connection is opened. We should be opening the serial port and passing all commands, instead of returning to the shell for each command.

**Comment by bryerton** [comment]
Potentially, see my email reply.

**Comment by bryerton** [comment]
https://pyserial.readthedocs.io/en/latest/pyserial_api.html

Review the notes under "open()" command, this may be fixable by us forcing
the RTS and DTR settings on open, it's likely we are seeing a platform
difference. This bug does not occur for me unless I force rtscts to True

**Comment by bryerton** [comment]
This should be resolved as of version 1.2.2
