### ISSUE TITLE
command and variable definitions

### ISSUE THREAD

**Issue by vpesudo** [MechanicalVentilatorMilano/mvm-control#4]
not clear if pressure refers to pressure after PV1 (PS3) or airway pressure (PS4). 
not clear what's the outcome of calib and calibv
These doubts arose for users of HW_v3.

**Comment by leyton-cern** [comment]
Hi Vicente,
"get pressure" refers to pressure at the valve (PS3):
https://github.com/NuclearInstruments/MVMFirmware/blob/master/ArduinoCorePP_PWM_hw_v3/ArduinoCorePP_PWM_hw_v3.ino#L1417

"get calib" calibrates the four pressure sensors by averaging over 100 readings. The MVM should be disconnected from patient and simulator.
https://github.com/NuclearInstruments/MVMFirmware/blob/master/ArduinoCorePP_PWM_hw_v3/ArduinoCorePP_PWM_hw_v3.ino#L1511

"get calibv" seems to return values associated to tidal volume calculation
https://github.com/NuclearInstruments/MVMFirmware/blob/master/ArduinoCorePP_PWM_hw_v3/ArduinoCorePP_PWM_hw_v3.ino#L1528

hope that helps,
michael

**Comment by bryerton** [comment]
Closing this issue, please re-open if there is something specific that can or should be changed in the mvm-control for this issue.
