### ISSUE TITLE
Settings field of data file

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#7]
Hi Bryerton,
I was asked in the analysis meeting to pass this bit of feedback to you:
The values of the various settings fields in the .json output are stored as strings and not as numbers. Could this be changed so that numbers are stored instead? 
Thanks

**Comment by bryerton** [comment]
Yes, I'll do this immediately.

**Comment by bryerton** [comment]
Resolved. New version is out 1.3.2 that fixes this, settings are now output as float or int respectively. This shouldn't have any effect on loading previously stored settings.
